import type { Metadata } from 'next';
import Link from 'next/link';
import { Navbar } from '@/components/layout/Navbar';
import { Footer } from '@/components/layout/Footer';
export const metadata: Metadata = { title: 'Investor Relations — FinWise AI', description: 'FinWise AI is raising ₹2 Crore seed round. India\'s AI financial OS for 14 crore+ underserved Indians.' };
export default function InvestorsPage() {
  return (<><Navbar /><main className="pt-20 pb-20"><div className="max-w-5xl mx-auto px-6"><div className="pt-14 pb-12 text-center"><div className="section-label">Investor Relations</div><h1 className="text-5xl font-extrabold text-white mb-5">We're Raising <span className="gradient-text">₹2 Crore Seed</span></h1><p className="text-xl text-slate-400 max-w-2xl mx-auto">18-month runway to ₹19.7Cr ARR and Series A readiness. Building the financial OS for India's 14 crore+ underserved investors.</p></div>
  <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-14">{[{v:'14Cr+',l:'Target users',c:'text-blue-400'},{v:'₹100Cr',l:'ARR target Year 3',c:'text-emerald-400'},{v:'7.5×',l:'LTV:CAC ratio',c:'text-amber-400'},{v:'75%',l:'Gross margin',c:'text-purple-400'}].map(s=><div key={s.l} className="card p-5 text-center"><div className={`text-2xl font-bold font-mono ${s.c}`}>{s.v}</div><div className="text-xs text-slate-400 mt-1">{s.l}</div></div>)}</div>
  <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-14">
    <div className="card p-7"><h2 className="text-xl font-bold text-white mb-5">Use of Funds</h2><div className="space-y-3">{[['Engineering team (8 people, 18 months)','₹1.2 Crore','bg-blue-500',60],['SEBI compliance + legal','₹20 Lakh','bg-teal-500',10],['AWS/Anthropic infra (5L users)','₹25 Lakh','bg-emerald-500',12],['Marketing + ET partnership','₹20 Lakh','bg-amber-500',10],['Product design + research','₹15 Lakh','bg-purple-500',7],['Contingency buffer','₹20 Lakh','bg-slate-500',10]].map(([name,amt,color,pct])=><div key={name as string} className="flex items-center gap-3"><div className="flex-1"><div className="flex justify-between text-sm mb-1"><span className="text-slate-300">{name as string}</span><span className="font-mono text-emerald-400">{amt as string}</span></div><div className="h-1.5 bg-slate-800 rounded-full overflow-hidden"><div className={`h-full rounded-full ${color as string}`} style={{width:`${pct}%`}} /></div></div></div>)}</div></div>
    <div className="card p-7"><h2 className="text-xl font-bold text-white mb-5">3-Year Projections</h2><table className="w-full text-sm"><thead><tr><td className="text-slate-500 pb-2">Metric</td><td className="text-slate-500 pb-2 text-right">Yr 1</td><td className="text-slate-500 pb-2 text-right">Yr 2</td><td className="text-slate-500 pb-2 text-right">Yr 3</td></tr></thead><tbody>{[['Free users','50K','3L','15L'],['Paid users','4K','24K','1.2L'],['Total ARR','₹2.9Cr','₹19.7Cr','₹100Cr'],['Gross margin','72%','75%','78%'],['Team size','8','25','80']].map(([m,...vals])=><tr key={m as string} className="border-t border-white/5"><td className="py-2 text-slate-300">{m as string}</td>{(vals as string[]).map((v,i)=><td key={i} className={`py-2 text-right font-mono ${m==='Total ARR'?'text-emerald-400 font-bold':'text-white'}`}>{v}</td>)}</tr>)}</tbody></table></div>
  </div>
  <div className="grid grid-cols-1 md:grid-cols-3 gap-5 mb-14">{[{icon:'💰',t:'₹2 Crore Seed',d:'Seeking from angel investors and early-stage VCs. 18-month runway to hit Series A metrics.'},{icon:'🤝',t:'ET Partnership',d:'Distribution deal with Economic Times — 5 crore monthly users, near-zero CAC of ₹800/user.'},{icon:'🏆',t:'Why Invest Now',d:'No dominant AI financial advisor in India yet. 18-month first-mover window. Team with banking + AI + product expertise.'}].map(c=><div key={c.t} className="card p-6 text-center"><span className="text-4xl block mb-3">{c.icon}</span><h3 className="font-bold text-white mb-2">{c.t}</h3><p className="text-sm text-slate-400">{c.d}</p></div>)}</div>
  <div className="card p-8 text-center"><h2 className="text-2xl font-bold text-white mb-3">Request Investor Deck</h2><p className="text-slate-400 mb-6">We share our full pitch deck, financial model, and cap table with qualified investors under NDA.</p><a href="mailto:sumitranjanhisu@gmail.com" className="btn-primary">sumitranjanhisu@gmail.com →</a></div>
  </div></main><Footer /></>);
}
