import type { Metadata } from 'next';
import Link from 'next/link';
import { Navbar } from '@/components/layout/Navbar';
import { Footer } from '@/components/layout/Footer';
export const metadata: Metadata = { title: 'Careers — FinWise AI', description: 'Join FinWise AI and help democratize financial planning for India. Open roles in engineering, product, and finance.' };
const roles = [
  { title: 'Senior Full Stack Engineer', team: 'Engineering', location: 'Bengaluru / Remote', type: 'Full-time', desc: 'Build the AI infrastructure powering financial advice for 1 lakh+ Indians. Next.js, TypeScript, Firebase, Python.' },
  { title: 'AI/ML Engineer', team: 'Engineering', location: 'Bengaluru / Remote', type: 'Full-time', desc: 'Fine-tune LLMs for Indian financial context. Build document parsers for Form 16, CAMS statements. Python, PyTorch.' },
  { title: 'Product Manager', team: 'Product', location: 'Bengaluru', type: 'Full-time', desc: 'Own the AI advisor product roadmap. Work directly with users to understand financial pain points and translate them into features.' },
  { title: 'CA / Financial Domain Expert', team: 'Finance', location: 'Remote', type: 'Full-time / Contract', desc: 'Ensure our tax calculations, investment advice logic, and SEBI compliance are always accurate. CA qualification required.' },
  { title: 'Growth Marketing Manager', team: 'Growth', location: 'Bengaluru / Remote', type: 'Full-time', desc: 'Drive user acquisition through content, SEO, and partnerships. Deep understanding of Indian personal finance audience.' },
  { title: 'Financial Content Writer (Hindi)', team: 'Content', location: 'Remote', type: 'Contract', desc: 'Create engaging Hindi financial content — articles, explainers, social media. CA or finance background preferred.' },
];
const perks = ['Competitive salary + meaningful equity', 'Remote-first culture', 'Health insurance for you and family', '₹50,000/year learning & development budget', 'Work on problems that genuinely matter to millions', 'Flat hierarchy — your voice matters from Day 1'];
export default function CareersPage() {
  return (<><Navbar /><main className="pt-20 pb-20"><div className="max-w-5xl mx-auto px-6"><div className="pt-14 pb-12 text-center"><div className="section-label">Join us</div><h1 className="text-5xl font-extrabold text-white mb-5">Help Build the Financial OS<br /><span className="gradient-text">for 1.4 Billion Indians</span></h1><p className="text-xl text-slate-400 max-w-2xl mx-auto">We're a small team solving a big problem. If you're excited about making financial expertise accessible to every Indian, we want to hear from you.</p></div><div className="grid grid-cols-2 md:grid-cols-3 gap-4 mb-16">{perks.map(p => (<div key={p} className="card p-4 flex items-start gap-3"><span className="text-emerald-400 mt-0.5 flex-shrink-0">✓</span><span className="text-sm text-slate-300">{p}</span></div>))}</div><div className="section-label mb-6">Open Roles</div><div className="space-y-4 mb-16">{roles.map(r => (<div key={r.title} className="card p-6"><div className="flex flex-col md:flex-row md:items-start justify-between gap-4"><div><h3 className="text-lg font-bold text-white mb-1">{r.title}</h3><div className="flex flex-wrap gap-2 mb-3"><span className="badge badge-blue">{r.team}</span><span className="badge badge-purple">{r.location}</span><span className="badge badge-green">{r.type}</span></div><p className="text-sm text-slate-400 leading-relaxed">{r.desc}</p></div><Link href={`/contact?role=${encodeURIComponent(r.title)}`} className="btn-primary btn-sm whitespace-nowrap flex-shrink-0">Apply Now</Link></div></div>))}</div><div className="card p-8 text-center"><h2 className="text-2xl font-bold text-white mb-3">Don't See Your Role?</h2><p className="text-slate-400 mb-6">We're always looking for exceptional people. Send us your resume and tell us how you'd make FinWise AI better.</p><Link href="mailto:sumitranjanhisu@gmail.com" className="btn-primary">Send Open Application</Link></div></div></main><Footer /></>);
}
