import type { Metadata } from 'next';
import Link from 'next/link';
import { Navbar } from '@/components/layout/Navbar';
import { Footer } from '@/components/layout/Footer';
export const metadata: Metadata = { title: 'Community — FinWise AI', description: 'Join the FinWise AI community. Discuss financial planning, share tips, learn from other Indians building wealth.' };
export default function CommunityPage() {
  return (<><Navbar /><main className="pt-20 pb-20"><div className="max-w-5xl mx-auto px-6"><div className="pt-14 pb-12 text-center"><div className="section-label">Community</div><h1 className="text-4xl font-extrabold text-white mb-4">Join 50,000+ Indians<br /><span className="gradient-text">Building Wealth Together</span></h1><p className="text-xl text-slate-400 max-w-xl mx-auto mb-8">Ask questions, share learnings, and discuss financial strategies with other FinWise AI users. Hindi and English welcome.</p><div className="flex flex-wrap justify-center gap-4"><a href="https://discord.gg/finwiseai" target="_blank" rel="noopener noreferrer" className="btn-primary btn-lg">Join Discord Server</a><a href="https://t.me/finwiseai" target="_blank" rel="noopener noreferrer" className="btn-secondary btn-lg">Join Telegram</a></div></div>
  <div className="grid grid-cols-1 md:grid-cols-3 gap-5 mb-14">{[{icon:'💬',t:'Discord Server',d:'Real-time discussions, voice channels for weekly Q&A sessions with our finance team, and dedicated channels for FIRE planning, tax, and MF discussions.',members:'12,000+ members',link:'Join Discord'},{icon:'📱',t:'Telegram Group',d:'Quick questions and daily market nudges. Our AI posts the Money Tip of the Day every morning. Most active channel for Hindi-speaking users.',members:'28,000+ members',link:'Join Telegram'},{icon:'🐦',t:'Twitter / X',d:'Financial education threads, product updates, and real-time market commentary from our team. Follow for free daily tips.',members:'8,000 followers',link:'Follow @finwiseai'}].map(c=><div key={c.t} className="card p-6 text-center"><span className="text-4xl block mb-3">{c.icon}</span><h3 className="font-bold text-white mb-2">{c.t}</h3><p className="text-sm text-slate-400 leading-relaxed mb-3">{c.d}</p><div className="text-xs text-emerald-400 font-semibold mb-4">{c.members}</div><button className="btn-secondary btn-sm w-full">{c.link}</button></div>)}</div>
  <div className="card p-8"><h2 className="text-xl font-bold text-white mb-5">Community Guidelines</h2><div className="grid grid-cols-1 md:grid-cols-2 gap-4">{['Be respectful — no personal attacks or judgment about financial situations','No spam, promotional content, or unsolicited financial product recommendations','Do not share specific stock tips — this is an educational community','Verify information before acting — always consult SEBI-registered advisors for major decisions','Hindi and English both welcome — translate if you can for inclusivity','Report scams or suspicious advice to moderators immediately'].map(g=><div key={g} className="flex items-start gap-2 text-sm text-slate-300"><span className="text-blue-400 flex-shrink-0 mt-0.5">•</span>{g}</div>)}</div></div></div></main><Footer /></>);
}
