import type { Metadata } from 'next';
import Link from 'next/link';
import { Navbar } from '@/components/layout/Navbar';
import { Footer } from '@/components/layout/Footer';
export const metadata: Metadata = { title: 'Blog — FinWise AI', description: 'Financial planning guides, tax tips, investment advice, and personal finance education for Indians. In Hindi and English.' };
const posts = [
  { slug:'old-vs-new-tax-regime-2025-26', category:'Tax Planning', title:'Old vs New Tax Regime FY 2025-26: Complete Comparison with Numbers', date:'Mar 15, 2026', readTime:'8 min', summary:'The new regime now has ₹75K standard deduction. But old regime still wins for most salaried professionals earning ₹10-20L. Here\'s the exact breakeven calculation.' },
  { slug:'fire-planning-india', category:'FIRE Planning', title:'How to Retire at 45 in India: The Complete FIRE Guide', date:'Mar 10, 2026', readTime:'12 min', summary:'The 4% rule, how much corpus you need at different expense levels, which funds to use, and the exact SIP amounts by starting age. With real Indian market data.' },
  { slug:'mf-overlap-problem', category:'Mutual Funds', title:'The Hidden Mutual Fund Problem No One Talks About: Fund Overlap', date:'Mar 5, 2026', readTime:'6 min', summary:'67% of Indians with 5+ mutual funds have significant overlap. You\'re not diversified — you\'re just paying more expense ratio for the same stocks.' },
  { slug:'sip-vs-lumpsum', category:'Investing', title:'SIP vs Lumpsum: When is Each Better? (With Mathematical Analysis)', date:'Feb 28, 2026', readTime:'7 min', summary:'SIP always wins in volatile markets. Lumpsum wins in sustained bull runs. Here\'s how to decide which one to use for your situation.' },
  { slug:'emergency-fund-india', category:'Financial Planning', title:'Emergency Fund in India: How Much, Where to Keep, and When to Use It', date:'Feb 20, 2026', readTime:'5 min', summary:'6 months of expenses is the target. But where you keep it matters as much as how much. Liquid funds vs savings account vs FD — we compare them all.' },
  { slug:'nps-tax-benefit', category:'Tax Planning', title:'NPS: The Most Underused Tax Deduction (₹50,000 Extra Savings)', date:'Feb 15, 2026', readTime:'6 min', summary:'80CCD(1B) gives you ₹50,000 extra deduction over and above 80C. That\'s ₹15,000+ saved if you\'re in the 30% bracket. Most people don\'t know about it.' },
];
const categories = ['All', 'Tax Planning', 'Mutual Funds', 'FIRE Planning', 'Investing', 'Financial Planning', 'Insurance'];
export default function BlogPage() {
  return (<><Navbar /><main className="pt-20 pb-20"><div className="max-w-6xl mx-auto px-6"><div className="pt-14 pb-12 text-center"><div className="section-label">FinWise AI Blog</div><h1 className="text-4xl md:text-5xl font-extrabold text-white mb-4">Financial Education<br /><span className="gradient-text">For Every Indian</span></h1><p className="text-slate-400 text-lg max-w-xl mx-auto">Practical financial guides in plain Hindi and English. No jargon, no agenda, just useful information.</p></div>
  <div className="flex flex-wrap gap-2 mb-10 justify-center">{categories.map(c=><button key={c} className={`px-4 py-2 rounded-xl text-sm font-medium transition-colors ${c==='All'?'bg-blue-600 text-white':'bg-slate-800 text-slate-400 border border-white/10 hover:text-white'}`}>{c}</button>)}</div>
  <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">{posts.map(p=><article key={p.slug} className="card-hover p-6"><span className="badge badge-blue text-xs mb-3 inline-block">{p.category}</span><h2 className="font-bold text-white text-lg leading-snug mb-3 hover:text-blue-300 transition-colors"><Link href={`/blog/${p.slug}`}>{p.title}</Link></h2><p className="text-sm text-slate-400 leading-relaxed mb-4">{p.summary}</p><div className="flex items-center justify-between text-xs text-slate-500"><span>{p.date}</span><span>{p.readTime} read</span></div></article>)}</div>
  <div className="mt-14 card p-8 text-center"><h2 className="text-xl font-bold text-white mb-3">Get Weekly Financial Tips</h2><p className="text-slate-400 mb-5">Every Sunday — one actionable tip to improve your financial health. No spam. Unsubscribe anytime.</p><div className="flex gap-3 max-w-md mx-auto"><input type="email" className="input flex-1" placeholder="your@email.com" /><button className="btn-primary whitespace-nowrap">Subscribe</button></div></div></div></main><Footer /></>);
}
