import type { Metadata } from 'next';
import Link from 'next/link';
import { Navbar } from '@/components/layout/Navbar';
import { Footer } from '@/components/layout/Footer';
export const metadata: Metadata = { title: 'For Banks & NBFCs — FinWise AI', description: 'White-label AI financial advisor for banks and NBFCs. SDK integration in 1 week. Customer intelligence, loan underwriting, regulatory reporting.' };
export default function BankingPage() {
  return (<><Navbar /><main className="pt-20 pb-20"><div className="max-w-6xl mx-auto px-6"><div className="pt-14 pb-14 text-center"><div className="section-label">For Banks, NBFCs & Fintech Platforms</div><h1 className="text-5xl font-extrabold text-white mb-5">Add AI Financial Advisory<br /><span className="gradient-text">to Your App in 1 Week</span></h1><p className="text-xl text-slate-400 max-w-2xl mx-auto mb-8">Your 1 crore customers deserve world-class financial advice. FinWise AI's white-label SDK gives them exactly that — under your brand, in your app, generating revenue for you.</p><div className="flex flex-wrap justify-center gap-4"><Link href="/contact?enterprise=true" className="btn-primary btn-lg">Schedule Enterprise Demo</Link><Link href="/docs" className="btn-secondary btn-lg">View API Documentation</Link></div></div>
  <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-14">{[{icon:'🔌',title:'White-Label SDK Integration',desc:'Plug FinWise AI into your iOS, Android, or Web banking app in under 1 week. Our React Native and Web components are drop-in ready. Your colors, your logo, your brand experience — powered entirely by our AI engine.',benefit:'Zero development cost on your side. Integration engineer provided for first 30 days.'},{icon:'🎯',title:'Customer Intelligence Engine',desc:'Anonymized financial behavior analysis helps you cross-sell products at the right moment. AI predicts who needs a home loan, FD, or credit card upgrade — before they ask. Life event detection: marriage, baby, house purchase signals.',benefit:'3× improvement in cross-sell conversion rates vs generic promotional campaigns.'},{icon:'📋',title:'Regulatory Reporting AI',desc:'RBI returns auto-populated from your transaction data. Stress testing narrative generation. CIBIL and credit risk narrative generation. Board-ready financial health summaries in minutes. SARFAESI compliance documentation.',benefit:'Reduce regulatory reporting time by 70%. Eliminate manual data entry errors.'},{icon:'🌐',title:'NBFC Loan Underwriting',desc:'AI credit scoring from bank statements, ITR, mutual fund portfolio, and social signals. Alternative data approach beyond CIBIL. Fraud pattern detection from spending behavior. Loan decision in 60 seconds.',benefit:'40% reduction in NPAs through better underwriting. 10× faster loan processing.'}].map(f=><div key={f.title} className="card p-6"><div className="flex items-center gap-3 mb-3"><span className="text-3xl">{f.icon}</span><h3 className="font-bold text-white">{f.title}</h3></div><p className="text-sm text-slate-400 leading-relaxed mb-3">{f.desc}</p><div className="bg-emerald-900/20 border border-emerald-800/30 rounded-xl p-3 text-xs text-emerald-300">💡 {f.benefit}</div></div>)}</div>
  <div className="card p-8"><div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-center"><div><h2 className="text-2xl font-bold text-white mb-3">Enterprise Pricing</h2><p className="text-slate-400 mb-4 leading-relaxed">Custom pricing from ₹15L/year based on Monthly Active Users. Revenue share model available for banks. Volume discounts for NBFCs and fintech platforms.</p><div className="space-y-2">{['SOC 2 Type II compliance','SEBI guidelines adherence','Dedicated compliance officer','99.9% SLA guaranteed','Dedicated integration engineer','Custom security review on request'].map(f=><div key={f} className="flex items-center gap-2 text-sm text-slate-300"><span className="text-emerald-400">✓</span>{f}</div>)}</div></div><div className="text-center"><h3 className="text-lg font-bold text-white mb-3">Ready to Talk?</h3><p className="text-slate-400 text-sm mb-5">Our enterprise team responds within 24 hours. We'll send a detailed proposal within 3 business days.</p><Link href="/contact?enterprise=true" className="btn-primary">Schedule Demo →</Link><p className="text-xs text-slate-500 mt-3">sumitranjanhisu@gmail.com | +91 73660 06363</p></div></div></div></div></main><Footer /></>);
}
