import type { Metadata } from 'next';
import { Navbar } from '@/components/layout/Navbar';
import { Footer } from '@/components/layout/Footer';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'FinWise AI Terms of Service — Rules, responsibilities, and your rights when using our platform.',
};

const terms = [
  {
    title: '1. Acceptance of Terms',
    content: `By creating an account or using FinWise AI ("the Platform"), you agree to be bound by these Terms of Service ("Terms"), our Privacy Policy, and all applicable Indian laws and regulations.

If you are using FinWise AI on behalf of a business, you represent that you have authority to bind that business to these Terms.

**Age Requirement:** You must be at least 18 years old to use FinWise AI. By using our platform, you confirm that you meet this requirement.

We reserve the right to modify these Terms at any time. Continued use after notification of changes constitutes acceptance.`,
  },
  {
    title: '2. Not Investment Advice — SEBI Disclaimer',
    content: `**IMPORTANT: FinWise AI is NOT a SEBI-registered Investment Adviser.**

All content, analysis, calculations, and recommendations provided by FinWise AI are:
- For **educational and informational purposes only**
- Generated by artificial intelligence and may contain errors
- **Not a substitute for advice from a SEBI-registered Investment Adviser**
- Not tailored to your complete financial situation unless you have provided accurate and complete information

**Mutual fund investments are subject to market risks. Past performance is not indicative of future returns.**

You acknowledge that:
1. You will independently verify all information before making financial decisions
2. FinWise AI bears no responsibility for financial losses arising from decisions based on platform content
3. You should consult a qualified financial advisor for significant financial decisions
4. Tax calculations are estimates based on stated assumptions and may not reflect your exact liability`,
  },
  {
    title: '3. Account Registration and Security',
    content: `**Registration:** You must provide accurate, complete, and current information when creating your account.

**Account Security:** You are responsible for:
- Maintaining the confidentiality of your login credentials
- All activities that occur under your account
- Immediately notifying us of any unauthorized access at sumitranjanhisu@gmail.com

**One Account per User:** You may not create multiple accounts or share accounts with others.

**Account Suspension:** We reserve the right to suspend or terminate accounts that:
- Violate these Terms
- Engage in fraudulent activity
- Attempt to reverse-engineer or abuse our platform
- Use our AI advisor for illegal purposes`,
  },
  {
    title: '4. Subscription Plans and Billing',
    content: `**Plans:** FinWise AI offers Starter (Free), Pro (₹499/month), Business (₹1,299/month), and Professional (₹3,999/month) plans.

**Billing:** Subscriptions are billed monthly or annually in advance via Razorpay. All amounts are in Indian Rupees (INR) and inclusive of applicable GST.

**Auto-renewal:** Subscriptions automatically renew unless cancelled at least 24 hours before the renewal date.

**Free Trial:** New users may receive a 14-day free trial of paid plans. Credit card details are required but not charged during the trial period.

**Refund Policy:** We offer a 7-day money-back guarantee for new subscriptions. Refund requests must be submitted to sumitranjanhisu@gmail.com within 7 days of the charge. Annual plan refunds are prorated.

**Plan Changes:** You may upgrade or downgrade your plan at any time. Upgrades take effect immediately; downgrades take effect at the next billing cycle.

**Enterprise/B2B:** Bank and NBFC white-label agreements are governed by separate enterprise contracts.`,
  },
  {
    title: '5. Acceptable Use Policy',
    content: `You agree NOT to use FinWise AI to:

**Prohibited Activities:**
- Provide false financial information to manipulate AI recommendations
- Attempt to access other users' accounts or data
- Reverse engineer, decompile, or attempt to extract our AI models or algorithms
- Use our platform for money laundering, tax evasion, or other illegal financial activities
- Scrape or systematically extract data from our platform via automated means
- Share account access with others or resell our services
- Upload malicious files or attempt to compromise our systems
- Use our AI advisor to generate advice you intend to pass off as professional financial advice to third parties without disclosing the AI source

**API Users:** Additional rate limits and acceptable use policies apply to API access. See our API documentation.`,
  },
  {
    title: '6. Intellectual Property',
    content: `**Our IP:** FinWise AI, its logo, the underlying AI models, algorithms, financial calculation methodologies, and all platform content are owned by FinWise AI Pvt. Ltd. and protected by Indian and international intellectual property laws.

**Your Data:** You retain ownership of all financial data you upload to the platform. You grant us a limited license to process this data solely to provide our services to you.

**AI Output:** Financial analyses, plans, and recommendations generated by our AI are provided as tools for your personal use. You may not resell or distribute AI-generated content from our platform as your own professional advice.

**Feedback:** Any feedback, suggestions, or feature requests you submit may be used by us without obligation to you.`,
  },
  {
    title: '7. Data and Privacy',
    content: `Your use of FinWise AI is also governed by our Privacy Policy, which is incorporated into these Terms by reference.

**Financial Document Processing:** Documents you upload (Form 16, CAMS statements, etc.) are processed securely and used only to provide your requested analysis.

**AI Training:** We do not use your personal financial data to train our AI models. AI processing is done via API calls to Anthropic with appropriate data protection agreements in place.

**Data Portability:** You may export all your data at any time from Settings > Export Data. Upon account deletion, all data is purged within 30 days.`,
  },
  {
    title: '8. Limitation of Liability',
    content: `**TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW:**

FinWise AI Pvt. Ltd. shall not be liable for:
- Any financial losses arising from decisions made based on platform content
- Inaccuracies in AI-generated financial analysis or tax calculations
- Service interruptions or data loss due to technical issues beyond our control
- Third-party services integrated with our platform (Razorpay, AWS, Anthropic)
- Market losses from investments made following platform suggestions

**Maximum Liability:** Our total liability to you for any claim shall not exceed the amount you paid to us in the 12 months preceding the claim.

**Essential Basis:** The above limitations are an essential basis of the bargain between you and FinWise AI. Some jurisdictions do not allow certain limitations — in such cases, our liability is limited to the maximum extent permitted by law.`,
  },
  {
    title: '9. Dispute Resolution',
    content: `**Governing Law:** These Terms are governed by the laws of India. The Courts of Bengaluru, Karnataka shall have exclusive jurisdiction.

**Informal Resolution:** Before filing any legal claim, you agree to contact us at sumitranjanhisu@gmail.com and attempt to resolve the dispute informally for 30 days.

**Arbitration:** If informal resolution fails, disputes shall be resolved through arbitration under the Arbitration and Conciliation Act, 1996. The seat of arbitration shall be Bengaluru.

**Consumer Protection:** Nothing in these Terms limits your rights under the Consumer Protection Act, 2019.

**Grievance Officer:** Anita Krishnan, sumitranjanhisu@gmail.com, +91-98765-43211. Response within 30 days.`,
  },
  {
    title: '10. Termination',
    content: `**By You:** You may close your account at any time from Settings > Account > Delete Account. Paid subscriptions remain active until the end of the billing period.

**By Us:** We may suspend or terminate your access immediately if you violate these Terms, engage in fraudulent activity, or for any other reason with 30 days notice (except in cases of serious violations).

**Effect of Termination:** Upon termination, your right to use the platform ceases. We will process data deletion within 30 days per our Privacy Policy.

**Survival:** Sections on intellectual property, limitation of liability, dispute resolution, and the SEBI disclaimer survive termination.`,
  },
  {
    title: '11. Contact',
    content: `**FinWise AI Pvt. Ltd.**
CIN: U72900KA2026PTC123456
Registered Office: 123, KIIT University, Bhubaneswar, Odisha — 751024

**Legal Enquiries:** sumitranjanhisu@gmail.com
**Billing Support:** sumitranjanhisu@gmail.com
**Technical Support:** sumitranjanhisu@gmail.com
**SEBI/Compliance:** compliance@finwise.ai

**Last Updated:** March 22, 2026 | **Version:** 3.0`,
  },
];

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="pt-24 pb-20 min-h-screen">
        <div className="max-w-4xl mx-auto px-6">
          <div className="mb-12">
            <div className="badge badge-blue mb-4">Legal</div>
            <h1 className="text-4xl font-extrabold text-white mb-4">Terms of Service</h1>
            <p className="text-slate-400 text-lg">Please read these terms carefully before using FinWise AI.</p>
            <div className="flex flex-wrap gap-4 mt-4 text-sm text-slate-500">
              <span>Last updated: March 22, 2026</span>
              <span>·</span>
              <span>Version 3.0</span>
            </div>
          </div>

          {/* SEBI Warning Box */}
          <div className="bg-amber-900/20 border border-amber-700/40 rounded-2xl p-6 mb-10">
            <div className="flex gap-3">
              <span className="text-2xl">⚠️</span>
              <div>
                <h2 className="font-bold text-amber-300 mb-2">Important: Not Investment Advice</h2>
                <p className="text-sm text-amber-200/70 leading-relaxed">
                  FinWise AI provides AI-generated financial education tools. It is NOT a SEBI-registered Investment Adviser. All content is for informational purposes only. Mutual fund investments are subject to market risks. Always consult a qualified financial advisor before making investment decisions.
                </p>
              </div>
            </div>
          </div>

          <div className="space-y-8">
            {terms.map((term) => (
              <section key={term.title} className="card p-8">
                <h2 className="text-xl font-bold text-white mb-5 pb-3 border-b border-white/10">{term.title}</h2>
                <div className="space-y-3">
                  {term.content.split('\n\n').map((para, i) => (
                    <p key={i} className="text-sm text-slate-300 leading-relaxed">
                      {para.split('**').map((part, j) =>
                        j % 2 === 1 ? <strong key={j} className="text-white font-semibold">{part}</strong> : part
                      )}
                    </p>
                  ))}
                </div>
              </section>
            ))}
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
