import type { Metadata } from 'next';
import Link from 'next/link';
import { Navbar } from '@/components/layout/Navbar';
import { Footer } from '@/components/layout/Footer';
export const metadata: Metadata = { title: 'NRI Financial Planning — FinWise AI', description: 'AI financial advisor for Non-Resident Indians. NRE/NRO account advice, DTAA tax treaties, repatriation planning, India investment strategy.' };
export default function NRIPage() {
  return (<><Navbar /><main className="pt-20 pb-20"><div className="max-w-5xl mx-auto px-6"><div className="pt-14 pb-14 text-center"><div className="section-label">NRI Financial Planning</div><h1 className="text-5xl font-extrabold text-white mb-5">Managing India Finances<br /><span className="gradient-text">from Anywhere in the World</span></h1><p className="text-xl text-slate-400 max-w-2xl mx-auto mb-8">NRI finances are uniquely complex — DTAA treaties, NRE vs NRO accounts, FEMA compliance, repatriation rules. FinWise AI is the only advisor that understands all of it.</p><Link href="/register" className="btn-primary btn-lg">Start Planning Free</Link></div>
  <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-14">{[{icon:'🌏',title:'NRE vs NRO Account Optimizer',desc:'Should you use NRE or NRO account for this investment? Which is better for repatriation? FinWise AI explains the tax implications of each account type for your specific country of residence and investment goal.',benefit:'Most NRIs use the wrong account type and pay unnecessary taxes.'},{icon:'📋',title:'DTAA Tax Treaty Guidance',desc:'India has DTAA (Double Taxation Avoidance Agreement) with 90+ countries. FinWise AI tells you exactly which DTAA clauses apply to your situation — whether you\'re in the US, UK, UAE, Singapore, or Australia.',benefit:'Proper DTAA planning saves most NRIs ₹50,000–₹2,00,000/year in double taxation.'},{icon:'💰',title:'India Investment Strategy',desc:'Which assets in India can NRIs invest in? (Equity MFs: yes. PPF: no. NPS: yes.) FinWise AI builds an India-specific investment portfolio recommendation accounting for your country\'s capital gains tax rules.',benefit:'Equity MF investments in India via NRE account are fully repatriable — most NRIs don\'t use this.'},{icon:'🔄',title:'Repatriation Planning',desc:'Planning to move money from India back to your country of residence? FinWise AI calculates the tax liability, FEMA compliance requirements, and optimal timing based on your TRC (Tax Residency Certificate) status.',benefit:'Poorly planned repatriation can trigger 30%+ taxes that are avoidable with planning.'}].map(f=><div key={f.title} className="card p-6"><div className="flex items-center gap-3 mb-3"><span className="text-3xl">{f.icon}</span><h3 className="font-bold text-white">{f.title}</h3></div><p className="text-sm text-slate-400 leading-relaxed mb-3">{f.desc}</p><div className="bg-emerald-900/20 border border-emerald-800/30 rounded-xl p-3 text-xs text-emerald-300">💡 {f.benefit}</div></div>)}</div>
  <div className="card p-8 text-center"><h2 className="text-2xl font-bold text-white mb-2">Pro Plan — ₹499/month</h2><p className="text-slate-400 mb-2">All NRI features included. Available in English. Supports US, UK, UAE, Singapore, Australia, Canada, and more.</p><p className="text-xs text-slate-500 mb-6">⚠️ NRI tax advice is complex. Please consult a SEBI-registered NRI financial advisor for personalized planning.</p><Link href="/register?plan=PRO" className="btn-primary btn-lg">Start Free Trial</Link></div></div></main><Footer /></>);
}
