import type { Metadata } from 'next';
import Link from 'next/link';
import { Navbar } from '@/components/layout/Navbar';
import { Footer } from '@/components/layout/Footer';
export const metadata: Metadata = { title: 'For Business Owners — FinWise AI', description: 'AI financial advisor for Indian entrepreneurs and business owners. Cash flow AI, GST tracking, loan advisor, salary vs dividend optimizer.' };
export default function BusinessPage() {
  return (<><Navbar /><main className="pt-20 pb-20"><div className="max-w-6xl mx-auto px-6"><div className="pt-14 pb-14 text-center"><div className="section-label">For Business Owners & Entrepreneurs</div><h1 className="text-5xl font-extrabold text-white mb-5">Stop Mixing Personal and<br /><span className="gradient-text">Business Finances Forever</span></h1><p className="text-xl text-slate-400 max-w-2xl mx-auto mb-8">India's first AI financial advisor built for business owners. Separate your finances, optimize your taxes, predict cash flow, and make smarter investment decisions — all in one place.</p><div className="flex flex-wrap justify-center gap-4"><Link href="/register?plan=BUSINESS" className="btn-primary btn-lg">Start Free Trial</Link><Link href="/pricing" className="btn-secondary btn-lg">See Business Plan ₹1,299/mo</Link></div></div>
  <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-14">{[{icon:'💼',title:'Business Cash Flow AI',desc:'Separate personal and business finances cleanly. AI monitors cash flow patterns, predicts lean months 3 months ahead, and recommends optimal working capital allocation. Never be caught off-guard by a slow month again.',benefit:'Average business owner identifies ₹30,000+/month in unnecessary business expenses.'},{icon:'📋',title:'Business Tax Optimizer',desc:'ITR-3/4 specific advice. Presumptive taxation (44AD/44ADA) vs regular analysis. Complete allowable business expenses checklist. Advance tax calculation with quarterly reminders. Salary vs dividend optimization for owner compensation.',benefit:'Most business owners overpay taxes by 20–35% due to missed deductions.'},{icon:'🏗️',title:'Loan Eligibility Analyser',desc:'Before applying for a business loan, FinWise AI analyses your financials and tells you exactly how much you qualify for from which lenders, at what rate, and whether the loan actually makes financial sense for your business.',benefit:'Avoid rejection and CIBIL impact. Know your eligibility before you apply.'},{icon:'📊',title:'Profit Reinvestment Optimizer',desc:'Should you invest business profits in mutual funds or reinvest in the business? AI models both scenarios with NPV, IRR, and opportunity cost analysis — tailored to your specific business type and growth stage.',benefit:'Most business owners don\'t separate business ROCE from market returns.'}].map(f=><div key={f.title} className="card p-6"><div className="flex items-center gap-3 mb-3"><span className="text-3xl">{f.icon}</span><h3 className="font-bold text-white">{f.title}</h3></div><p className="text-sm text-slate-400 leading-relaxed mb-3">{f.desc}</p><div className="bg-emerald-900/20 border border-emerald-800/30 rounded-xl p-3 text-xs text-emerald-300">💡 {f.benefit}</div></div>)}</div>
  <div className="card p-8 text-center"><h2 className="text-2xl font-bold text-white mb-2">Business Plan — ₹1,299/month</h2><p className="text-slate-400 mb-5">vs ₹15,000–50,000/year for a business CA. 14-day free trial, no card required.</p><Link href="/register?plan=BUSINESS" className="btn-primary btn-lg">Start Free Trial</Link></div></div></main><Footer /></>);
}
