import type { Metadata } from 'next';
import Link from 'next/link';
import { Navbar } from '@/components/layout/Navbar';
import { Footer } from '@/components/layout/Footer';
export const metadata: Metadata = { title: 'Couple Money Planner — FinWise AI', description: "India's first AI joint financial planning tool. Optimize HRA, NPS, SIP splits and combined net worth for couples." };
export default function CouplePage() {
  return (<><Navbar /><main className="pt-20 pb-20"><div className="max-w-5xl mx-auto px-6"><div className="pt-14 pb-14 text-center"><div className="section-label">Couple Money Planner</div><h1 className="text-5xl font-extrabold text-white mb-5">India's First AI Financial<br /><span className="gradient-text">Planner Built for Couples</span></h1><p className="text-xl text-slate-400 max-w-2xl mx-auto mb-8">Two incomes, two tax returns, two investment portfolios, shared goals. FinWise AI optimizes your combined financial picture so you keep more money and grow wealth faster — together.</p><Link href="/register" className="btn-primary btn-lg">Start Free — Plan Together</Link></div>
  <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-14">{[{icon:'💑',title:'Joint Income Optimization',desc:'Who should claim HRA? How should you split SIPs for maximum 80C benefit? Which partner should open NPS for 80CCD? FinWise AI models all optimization scenarios across both incomes and shows you the tax-efficient answer.',benefit:'Most couples leave ₹20,000–80,000/year in tax savings unclaimed due to suboptimal allocation.'},{icon:'🎯',title:'Combined Goal Planning',desc:'Dream home, children\'s education, early retirement — model all goals across combined income. AI shows the optimal monthly SIP split between both partners, accounting for each person\'s tax bracket and existing investments.',benefit:'Couples who plan jointly retire 3–5 years earlier on average vs independent planners.'},{icon:'📊',title:'Joint Net Worth Tracker',desc:'See your combined net worth across both partners: FDs, EPF, PPF, mutual funds, property, gold. Track monthly growth with contribution split visualization. Finally understand what you\'re building together.',benefit:'73% of Indian couples have never calculated their combined net worth.'},{icon:'🔗',title:'Shared Goal Accountability',desc:'Both partners see the same goals dashboard. Contributions from either side update in real-time. Nudges go to both partners for upcoming SIPs, tax deadlines, and goal milestones. Financial planning as a team sport.',benefit:'Couples with shared financial visibility report 40% fewer money-related conflicts.'}].map(f=><div key={f.title} className="card p-6"><div className="flex items-center gap-3 mb-3"><span className="text-3xl">{f.icon}</span><h3 className="font-bold text-white">{f.title}</h3></div><p className="text-sm text-slate-400 leading-relaxed mb-3">{f.desc}</p><div className="bg-emerald-900/20 border border-emerald-800/30 rounded-xl p-3 text-xs text-emerald-300">💡 {f.benefit}</div></div>)}</div>
  <div className="card p-8 text-center"><h2 className="text-2xl font-bold text-white mb-2">Family Plan — ₹799/month</h2><p className="text-slate-400 mb-5">Both partners + 1 parent profile. Everything in Pro, plus joint planning tools. One subscription for the whole family.</p><Link href="/register?plan=FAMILY" className="btn-primary btn-lg">Start Family Plan</Link></div></div></main><Footer /></>);
}
