import type { Metadata } from 'next';
import Link from 'next/link';
import { Navbar } from '@/components/layout/Navbar';
import { Footer } from '@/components/layout/Footer';
export const metadata: Metadata = { title: 'For Finance Professionals — FinWise AI', description: 'AI-powered platform for CAs, CFPs, and wealth managers. Manage 50 client portfolios, compliance copilot, AI-generated financial plans.' };
export default function ProfessionalPage() {
  return (<><Navbar /><main className="pt-20 pb-20"><div className="max-w-6xl mx-auto px-6"><div className="pt-14 pb-14 text-center"><div className="section-label">For CAs, CFPs & Wealth Managers</div><h1 className="text-5xl font-extrabold text-white mb-5">Manage 50 Client Portfolios<br /><span className="gradient-text">In the Time It Used to Take 5</span></h1><p className="text-xl text-slate-400 max-w-2xl mx-auto mb-8">FinWise AI is your AI-powered associate. Handle more clients, produce better plans, stay compliant, and grow your practice without burning out.</p><div className="flex flex-wrap justify-center gap-4"><Link href="/register?plan=PROFESSIONAL" className="btn-primary btn-lg">Start Free Trial</Link><Link href="/contact?enterprise=true" className="btn-secondary btn-lg">Schedule Demo</Link></div></div>
  <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-14">{[{icon:'📁',title:'Multi-Client Portfolio Manager',desc:'Manage up to 50 client profiles in one dashboard. Bulk CAMS upload — upload all client statements at once and get individual analyses. AI-generated PDF financial plans in your firm\'s branding. Progress tracking across all clients.',benefit:'Save 3 days per week on manual portfolio analysis and report generation.'},{icon:'⚖️',title:'Compliance Copilot',desc:'SEBI, AMFI, and IRDAI regulation alerts. KYC expiry tracking across all clients with advance warnings. Suitability documentation auto-generated for every recommendation. Complete audit trail maintained for each client.',benefit:'Never miss a compliance deadline or KYC renewal again.'},{icon:'📈',title:'Research Intelligence',desc:'Fund manager commentary analysis from every quarterly letter. FII/DII flow signal detection for sector rotation. Corporate action alerts (bonus, splits, mergers) across client holdings. Customizable alerts for your watchlist.',benefit:'Get the research output of a 5-analyst team with one subscription.'},{icon:'📄',title:'White-Label Client Reports',desc:'Generate client-facing reports with your firm\'s logo, colors, and branding. Reports include portfolio summary, performance analysis, rebalancing recommendations, and next steps. Exportable as PDF.',benefit:'Impress clients with professional reports that used to take 3 hours each.'}].map(f=><div key={f.title} className="card p-6"><div className="flex items-center gap-3 mb-3"><span className="text-3xl">{f.icon}</span><h3 className="font-bold text-white">{f.title}</h3></div><p className="text-sm text-slate-400 leading-relaxed mb-3">{f.desc}</p><div className="bg-emerald-900/20 border border-emerald-800/30 rounded-xl p-3 text-xs text-emerald-300">💡 {f.benefit}</div></div>)}</div>
  <div className="card p-8 text-center"><h2 className="text-2xl font-bold text-white mb-2">Professional Plan — ₹3,999/month</h2><p className="text-slate-400 mb-5">50 client profiles, bulk analysis, compliance copilot, white-label reports, API access. Pay for itself with your first 2 new clients.</p><Link href="/register?plan=PROFESSIONAL" className="btn-primary btn-lg">Start Free Trial</Link></div></div></main><Footer /></>);
}
