import type { Metadata } from 'next';
import { Navbar } from '@/components/layout/Navbar';
import { Footer } from '@/components/layout/Footer';
export const metadata: Metadata = { title: 'Press Kit — FinWise AI', description: 'FinWise AI press kit. Company facts, logos, founder headshots, and press coverage.' };
export default function PressPage() {
  return (<><Navbar /><main className="pt-20 pb-20"><div className="max-w-4xl mx-auto px-6"><div className="pt-14 pb-12"><div className="section-label">Press & Media</div><h1 className="text-4xl font-extrabold text-white mb-4">Press Kit</h1><p className="text-xl text-slate-400">Everything journalists and media professionals need to cover FinWise AI. For enquiries: <a href="mailto:sumitranjanhisu@gmail.com" className="text-blue-400 hover:text-blue-300">sumitranjanhisu@gmail.com</a></p></div>
  <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-10"><div className="card p-6"><h2 className="font-bold text-white mb-4">Company Facts</h2><table className="w-full text-sm"><tbody>{[['Founded','2024, Bengaluru, India'],['Founders','Arjun Sharma (CEO), Mehak Singhal, CTO)'],['Employees','8 full-time (hiring)'],['Users','1,00,000+'],['Funding','Pre-seed ₹50L; Raising ₹2Cr Seed'],['Revenue','₹2.9 Crore ARR (FY26)'],['Product','AI Financial Advisor — Web + iOS + Android'],['Category','FinTech / AI / Personal Finance']].map(([k,v])=><tr key={k as string} className="border-b border-white/5"><td className="py-2 text-slate-400">{k as string}</td><td className="py-2 text-white font-medium">{v as string}</td></tr>)}</tbody></table></div>
  <div className="card p-6"><h2 className="font-bold text-white mb-4">Key Messages</h2><div className="space-y-3">{["FinWise AI is democratizing financial planning for India's 95% underserved population","The company charges ₹499/month vs ₹25,000+/year for a human financial advisor","Powered by Claude AI (Anthropic), with deep Indian financial context","Supports 6 Indian languages including Hindi, Tamil, and Telugu","ET AI Hackathon 2026 finalist | Problem Statement #9 winner"].map(m=><div key={m} className="flex items-start gap-2 text-sm text-slate-300"><span className="text-blue-400 mt-0.5">•</span>{m}</div>)}</div></div></div>
  <div className="card p-6 mb-6"><h2 className="font-bold text-white mb-4">Download Assets</h2><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{[{t:'Logo (SVG)',icon:'🎨'},{t:'Logo (PNG)',icon:'🖼️'},{t:'App Screenshots',icon:'📱'},{t:'Founder Photos',icon:'👥'}].map(a=><button key={a.t} className="card p-4 text-center hover:border-white/20 transition-colors"><span className="text-2xl block mb-2">{a.icon}</span><span className="text-sm text-slate-300">{a.t}</span></button>)}</div></div>
  <div className="card p-6"><h2 className="font-bold text-white mb-4">Press Coverage</h2><div className="space-y-3">{[{pub:'Economic Times',title:'ET AI Hackathon 2026: FinWise AI wins PS#9 with AI Financial OS',date:'Mar 2026'},{pub:'YourStory',title:'This Bengaluru startup is building a CA for every Indian at ₹499/month',date:'Feb 2026'},{pub:'Inc42',title:'FinWise AI raises pre-seed to democratize financial planning',date:'Jun 2024'}].map(p=><div key={p.title} className="flex items-start justify-between gap-4 py-3 border-b border-white/5 last:border-0"><div><div className="text-xs font-bold text-blue-400 mb-0.5">{p.pub}</div><div className="text-sm text-white font-medium">{p.title}</div></div><span className="text-xs text-slate-500 flex-shrink-0">{p.date}</span></div>)}</div></div></div></main><Footer /></>);
}
